version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      VS_VERSION: 2019

  SECURE_VAR1:
    secure: u13nxV7AxZi6gDlC2qRcFw==

  SECURE_VAR2:
    secure: u13nxV7AxZi6gDlC2qRcFw==

configuration:
  - Release

platform:
  - Win32
#  - x64

build_script:
- cmd: >-
    echo PLATFORM        %PLATFORM%

    echo CONFIGURATION   %CONFIGURATION%
    
    if not defined SECURE_VAR1 echo SECURE_VAR1 is not defined

    if not defined SECURE_VAR2 echo SECURE_VAR2 is not defined
    
    "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -prerelease -products * -requires Microsoft.Component.MSBuild -property installationPath

    cmake --version

    cmake --help
