version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
    - SONAR_QUBE: Yes

    # second group
    - SONAR_QUBE: No

matrix:
  exclude:
    - configuration: Release
      SONAR_QUBE: Yes

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: >-
    echo PLATFORM        %PLATFORM%

    echo CONFIGURATION   %CONFIGURATION%
    
    echo my_variable     %my_variable%

    call secure-test.bat
