version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: >-
    echo PLATFORM        %PLATFORM%

    echo CONFIGURATION   %CONFIGURATION%

    echo "test" > test.txt

before_test:
- cmd: >-
    echo "before_test"

test_script:
- cmd: >-
    echo "test_script"

artifacts:
- path: '*.txt'
