version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
    - SONAR_QUBE: Yes
      my_variable:
        secure: 67KUU0QleOjNVnNjKF6NYA==

    # second group
    - SONAR_QUBE: No
      my_variable:
        secure: 67KUU0QleOjNVnNjKF6NYA==

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: >-
    echo PLATFORM        %PLATFORM%

    echo CONFIGURATION   %CONFIGURATION%
    
    echo my_variable     %my_variable%

    call secure-test.bat
