trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    exclude:
      - "*.md"
      - docs/*
      - .circleci/*
      - .cirrus.yml
      - .travis.yml
      - appveyor.yml
      - bitrise.yml
      - buddy.yml
      - codecov.yml
      - codefresh.yml
      - rocro.yml
      - shippable.yml
      - wercker.yml
      - Jenkinsfile

pr:
  branches:
    include:
      - master
      - develop
      - feature/*

jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: VS2017
    vmImage: 'VS2017-Win2016'
    displayName: VS2017
