trigger:
- master
- feature/*
pr:
- master

jobs:
- job: Win32_debug
  displayName: 'Windows Win32 Debug'
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    configuration: debug
    platform: Win32

  steps:
  - template: azure-pipelines-template.yml

- job: Win32_release
  displayName: 'Windows Win32 Release'
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    configuration: release
    platform: Win32

  steps:
  - template: azure-pipelines-template.yml

- job: x64_debug
  displayName: 'Windows x64 Debug'
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    configuration: debug
    platform: x64

  steps:
  - template: azure-pipelines-template.yml

- job: x64_release
  displayName: 'Windows x64 Release'
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    configuration: release
    platform: x64

  steps:
  - template: azure-pipelines-template.yml
