trigger:
- master
- feature/*
pr:
- master

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    maxParallel: 10
    matrix:
      Win32:
        BuildPlatform: 'Win32'
      Win64:
        BuildPlatform: 'x64'

  steps:
  - script: echo $(BuildPlatform)
    displayName: 'Test'
